# It contains all the configs required in the project

data_source: D:\Datasets\winequality_red.csv

artifacts:
  ARTIFACTS_DIR: artifacts
  RAW_LOCAL_DIR: raw_local_dir
  RAW_LOCAL_FILE: data.csv
  SPLIT_DATA_DIR: split_data_dir
  TRAIN_DF: train.csv
  TEST_DF: test.csv
  MODEL_DIR: model_dir
  MODEL_NAME: model.pkl

scores: scores.json
#  UPDATED_BASE_MODEL_NAME: updated_base_model.h5
#  CHECKPOINT_DIR: checkpoints
#  BASE_LOG_DIR: base_model_dir
#  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
#  CALLBACKS_DIR: callbacks
#
#source_download_dirs:
#  - path_to_data_1
#  - path_to_data_1
#
#local_data_dirs:
#  - path_to_local_data_1
#  - path_to_local_data_2
